### ISSUE TITLE
idea- set the South Pole arbitrarily

### ISSUE THREAD

**Issue by RoyWiggins** [mrgriscom/merc-extreme#30]
So, there's a unique Mobius transformation that's defined by three points on the sphere. It should be possible to map one arbitrary point to the South Pole, one to the north pole, and the third one somewhere along the equator. 

The result would not really be a Mercator projection, but it would let you put two arbitrary points at each infinite end of the Mercator result, rather than only antipodes. It would be conformal so the overall look would be similar.

**Comment by mrgriscom** [comment]
That is a cool idea but unfortunately the mercator projection formula and various optimizations around it are baked into the code in quite a few places. Adding what is essentially a new projection would be quite a bit of work.
