### ISSUE TITLE
Doesn't tile past north/south pole

### ISSUE THREAD

**Issue by RMcD94** [mrgriscom/merc-extreme#33]
You've got it tiling properly along the equator but for some reason it doesn't tile along longitude lines.

Mercator is square so shouldn't it be square?

http://static.boredpanda.com/blog/wp-content/uuuploads/fun-maps/fun-maps-39.jpg (this except rotated to be horizontal)

I want to see what Mercator looks like if the centre point is the north pole, so the most north point of the map should be the south pole and the most southern part should be the south pole

**Comment by mrgriscom** [comment]
I'm not sure I understand what you're asking. The map can already display true north pole at the north pole (or south pole), and supports 'north-up' (as opposed to default 'north to the right') orientation via the 'change orientation' arrow button.
