### ISSUE TITLE
Suggestion: Rotate the maps so that all the words are horizontal

### ISSUE THREAD

**Issue by ChristopherKing42** [mrgriscom/merc-extreme#34]
Add the ability to make the words horizontal. Hypothetically, this would be achieved by fetching the maps images from a rotated point of view. For example, when you rotate the map in google maps, the words stay horizontal. This allows you to rotate the words relative to the map.

**Comment by mrgriscom** [comment]
Having to keep track of an image tile's orientation in addition to its position would greatly complicate the caching mechanism. Also, not all tile providers support fetching tiles with rotated text, and not sure how long I would even trust google to keep providing this.
